In [ ]:
# !pip install pygame

In [1]:
import pygame
import sys
import numpy as np
import pandas as pd
from IPython.display import clear_output

pygame.init()
# init
icon = pygame.image.load('./icon.png')
screen = pygame.display.set_mode((480, 360))
pygame.display.set_caption('pocketPy v0.0')
pygame.display.set_icon(icon)

# border
def border(playerPosition, playerX, playerY):
    reSet = False
    y = playerY//40
    x = playerX//40
    nowMap(playerPosition, playerX, playerY)
    if playerPosition[int(y), int(x)] > 0:
        reSet = True
    else: 
        playerPosition[playerPosition == -999] = 0
        playerPosition[int(y), int(x)] = -999
    return reSet
# player
playerDirect = 'down'
playerImgSize = (20,30)
playerImg = {'down': pygame.transform.scale(pygame.image.load('./control_player/fore.png'), playerImgSize),
             'up': pygame.transform.scale(pygame.image.load('./control_player/back.png'), playerImgSize),
             'left': pygame.transform.scale(pygame.image.load('./control_player/left.png'), playerImgSize),
             'right': pygame.transform.scale(pygame.image.load('./control_player/right.png'), playerImgSize)}
playerPosition = np.arange(108).reshape(9,12) * 0
playerX = 235
playerY = 300
playerPosition[playerY//40, playerX//40] = -999
playerSpeed = .8

def player(direct, playerX, playerY):
    screen.blit(playerImg[direct], (playerX, playerY))

def playerMove(event):
    global playerX, playerY, playerDirect, playerPosition
    if event.type == pygame.KEYDOWN:
        reSet = False
        reSetX = playerX
        reSetY = playerY
        if event.key == pygame.K_UP:
            playerY -= playerSpeed
            playerDirect = 'up'
        if event.key == pygame.K_DOWN:
            playerY += playerSpeed
            playerDirect = 'down'
        if event.key == pygame.K_LEFT: 
            playerX -= playerSpeed
            playerDirect = 'left'
        if event.key == pygame.K_RIGHT: 
            playerX += playerSpeed
            playerDirect = 'right'
        reSet = border(playerPosition, playerX, playerY)
        if reSet:
            playerX = reSetX
            playerY = reSetY
                        
# background obj
tree_array = np.loadtxt('./background_obj/Tree/tree2.txt')
tree_nrow, tree_ncol = tree_array.shape
########################################################
# load object
# playerPosition = playerPosition + tree_array
########################################################
treeImg = pygame.transform.scale(pygame.image.load('./background_obj/Tree/tree.png'),(40,40))            
def tree(position_map):
    for y in range(tree_nrow):
        for x in range(tree_ncol):
            if position_map[y, x] == 1:
                screen.blit(treeImg, (x*40, y*40))

# bag ## @X@ player status file
# medicine
# medicine

def bag(leaveBag):
    bagImg = pygame.transform.scale(pygame.image.load('./bag/bag.png'), (120,80))
    while not leaveBag:
        screen.fill((255, 255, 255))
        screen.blit(bagImg, (0,0))
        for event in pygame.event.get():
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    leaveBag = True
                    
        pygame.display.update()
    
        
        
# Map
Map = np.zeros_like(tree_array)
Map = Map + tree_array

def bigMap():
    pass


def nowMap(playerPosition, playerX, playerY):
    global Map
    nowMapCol = int((playerX // 40) // 12)
    nowMapRow = int((playerY // 40) // 9)
    if nowMapRow*9 + 3 < Map.shape[0]:
        playerPosition = Map[nowMapRow*9+3:nowMapRow*9+3, :]
    
running = True
while running:
    screen.fill((0, 0, 0))   
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
            pygame.quit()
            sys.exit()
        # bag
        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_b:
                leaveBag = False
                bag(leaveBag)
        # position
            if event.key == pygame.K_p:
                clear_output()
                print(playerPosition)

    #player
    player(playerDirect,playerX, playerY)
    playerMove(event)
    #tree
    tree(tree_array)
    
    # renew 
    pygame.display.update()
pygame.quit()

[[   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0 -999    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0]]


SystemExit: 

C:\Users\777\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3339: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
