In [4]:
import pygame
import numpy as np
import pandas as pd
import sys
from IPython.display import clear_output

running = True
pygame.init()
screen = pygame.display.set_mode((480,360))
pygame.display.set_caption("PocketPyMap")
icon = pygame.image.load('./icon.png')
pygame.display.set_icon(icon)


# player
pointImg = pygame.transform.scale(pygame.image.load('./icon.png'), (40, 40))
pointx = 240
pointy = 180
speed = 20
def point(x, y):
    screen.blit(pointImg, (x, y))
def point_move(event):
    global pointx, pointy, treex, treey
    if event.type == pygame.KEYDOWN:
        if event.key == pygame.K_UP: pointy -= speed
        if event.key == pygame.K_DOWN: pointy += speed
        if event.key == pygame.K_LEFT: pointx -= speed
        if event.key == pygame.K_RIGHT: pointx += speed
        if event.key == pygame.K_SPACE:
            clear_output()
            print(pointx, pointy)
            treey = pointy // 40
            treex = pointx // 40
            tree_array[treey, treex] = 1
            print(tree_array)


# background obj
tree_array = np.loadtxt('../Game/background_obj/Tree/tree1.txt')
print(tree_array)
treeImg = pygame.transform.scale(pygame.image.load('./background_obj/tree.png'),(40,40))            
def tree(position_map):
    for y in range(9):
        for x in range(12):
            if position_map[y, x] == 1:
                screen.blit(treeImg, (x*40, y*40))

# gaming loop            
while running:
    screen.fill((0, 0, 0))
    tree(tree_array)
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
            pygame.quit()
            sys.exit()
        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_ESCAPE: running = False
        point_move(event)
            
    # point
    point(pointx, pointy)     
    pygame.display.update()
pygame.quit()

360 80
[[1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


SystemExit: 

In [5]:
np.savetxt('../Game/background_obj/Tree/tree1.txt',tree_array, fmt='%d')